server:
  port: 8080

spring:
  application:
    name: cerebral
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/cerebral
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 5000


logging:
  level:
    org:
      hibernate: INFO
