name: Build Spring Boot Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:



jobs:
  build:

    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - name: Start PostgreSQL container
        uses: docker://postgres:12
        with:
          env: POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password POSTGRES_DB=postgres
          ports: '5432:5432'

      - name: Wait for PostgreSQL container to start
        run: |
              set +e
              for i in {1..30}; do
                nc -z localhost 5432 && break
                echo "Waiting for PostgreSQL to start ($i/30)"
                sleep 1
              done
              set -e

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test

      - name: Stop PostgreSQL container
        run: |
          set +e
          docker container stop $(docker container ls --filter name=postgres -q)
          set -e
