name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Docker Daemon
        run: docker ps
      - name: Set up Docker
        uses: docker://alpine:3.12
        with:
          args: echo "Nothing to do."
        env:
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""
      - name: Start PostgreSQL container
        uses: docker://postgres:12
        with:
          env: POSTGRES_USER=postgres POSTGRES_PASSWORD=password POSTGRES_DB=postgres
          ports: '5432:5432'

      - name: Wait for PostgreSQL container to start
        run: |
              set +e
              for i in {1..30}; do
                nc -z localhost 5432 && break
                echo "Waiting for PostgreSQL to start ($i/30)"
                sleep 1
              done
              set -e
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
