# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
#name: cerebral-build
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: maven
#      - name: Install dependencies
#        run: mvn dependency:go-offline
#      - name: Clear Maven cache
#        run: rm -rf $HOME/.m2/repository
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker://alpine:3.12
        with:
          args: echo "Nothing to do."
        env:
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""
        id: setup_docker

      - name: Start PostgreSQL container
        uses: docker://postgres:12
        with:
          env: POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres POSTGRES_DB=postgres
          ports: '5432:5432'

      - name: Wait for PostgreSQL container to start
        run: |
              set +e
              for i in {1..30}; do
                nc -z localhost 5432 && break
                echo "Waiting for PostgreSQL to start ($i/30)"
                sleep 1
              done
              set -e

      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
