name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: openjdk
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
      - name: Check for dockerenv file
        run: sleep 100 
             docker run -it -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=postgres -p 5432:5432 postgres
